services:
  db:
    image: pgvector/pgvector:pg14
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ragdb
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./db_init.sh:/docker-entrypoint-initdb.d/init.sh:ro
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ragdb
      SOURCE_DIR: /opt/data/source
      PROCESSED_DIR: /opt/data/processed
      EMBEDDING_MODEL: intfloat/multilingual-e5-large
    depends_on:
      - db
    volumes:
      - ./data:/opt/data
volumes:
  pgdata:
